// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using todoapp_WebAPI.data;

#nullable disable

namespace todoapp_WebAPI.Migrations
{
    [DbContext(typeof(TodoAppDbContext))]
    [Migration("20231215222720_seed_TodoItem_data")]
    partial class seed_TodoItem_data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("todoapp_WebAPI.Models.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDone")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("TodoItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Todo Item 1",
                            isDone = false
                        },
                        new
                        {
                            Id = 2,
                            Title = "Todo Item 1",
                            isDone = false
                        },
                        new
                        {
                            Id = 3,
                            Title = "Todo Item 1",
                            isDone = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
